length_in_x: 2.5
length_in_y: 2.5
position_x: 0.0
position_y: 0.0
resolution: 0.07
min_variance: 0.000009
max_variance: 0.05
mahalanobis_distance_threshold: 100000.0
multi_height_noise: 0.0000009
enable_visibility_cleanup: True
scanning_duration: 0.15

