point_cloud_topic: "/snappy/snappy_stereo/point_cloud"
map_frame_id: "world"
robot_base_frame_id: "cam_left"
robot_pose_with_covariance_topic: "/vislam/pose"
robot_pose_cache_size: 200
track_point_frame_id: "cam_left"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0

